/* automatically generated by rust-bindgen 0.71.1 */
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
pub const LIMINE_H: u32 = 1;
pub const LIMINE_MEDIA_TYPE_GENERIC: u32 = 0;
pub const LIMINE_MEDIA_TYPE_OPTICAL: u32 = 1;
pub const LIMINE_MEDIA_TYPE_TFTP: u32 = 2;
pub const LIMINE_FIRMWARE_TYPE_X86BIOS: u32 = 0;
pub const LIMINE_FIRMWARE_TYPE_EFI32: u32 = 1;
pub const LIMINE_FIRMWARE_TYPE_EFI64: u32 = 2;
pub const LIMINE_FIRMWARE_TYPE_SBI: u32 = 3;
pub const LIMINE_FRAMEBUFFER_RGB: u32 = 1;
pub const LIMINE_PAGING_MODE_X86_64_4LVL: u32 = 0;
pub const LIMINE_PAGING_MODE_X86_64_5LVL: u32 = 1;
pub const LIMINE_PAGING_MODE_X86_64_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_X86_64_DEFAULT: u32 = 0;
pub const LIMINE_PAGING_MODE_AARCH64_4LVL: u32 = 0;
pub const LIMINE_PAGING_MODE_AARCH64_5LVL: u32 = 1;
pub const LIMINE_PAGING_MODE_AARCH64_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_AARCH64_DEFAULT: u32 = 0;
pub const LIMINE_PAGING_MODE_RISCV_SV39: u32 = 0;
pub const LIMINE_PAGING_MODE_RISCV_SV48: u32 = 1;
pub const LIMINE_PAGING_MODE_RISCV_SV57: u32 = 2;
pub const LIMINE_PAGING_MODE_RISCV_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_RISCV_DEFAULT: u32 = 1;
pub const LIMINE_PAGING_MODE_LOONGARCH_4LVL: u32 = 0;
pub const LIMINE_PAGING_MODE_LOONGARCH_MIN: u32 = 0;
pub const LIMINE_PAGING_MODE_LOONGARCH_DEFAULT: u32 = 0;
pub const LIMINE_MP_RESPONSE_X86_64_X2APIC: u32 = 1;
pub const LIMINE_MP_REQUEST_X86_64_X2APIC: u32 = 1;
pub const LIMINE_MEMMAP_USABLE: u32 = 0;
pub const LIMINE_MEMMAP_RESERVED: u32 = 1;
pub const LIMINE_MEMMAP_ACPI_RECLAIMABLE: u32 = 2;
pub const LIMINE_MEMMAP_ACPI_NVS: u32 = 3;
pub const LIMINE_MEMMAP_BAD_MEMORY: u32 = 4;
pub const LIMINE_MEMMAP_BOOTLOADER_RECLAIMABLE: u32 = 5;
pub const LIMINE_MEMMAP_EXECUTABLE_AND_MODULES: u32 = 6;
pub const LIMINE_MEMMAP_FRAMEBUFFER: u32 = 7;
pub const LIMINE_MEMMAP_ACPI_TABLES: u32 = 8;
pub const LIMINE_INTERNAL_MODULE_REQUIRED: u32 = 1;
pub const LIMINE_INTERNAL_MODULE_COMPRESSED: u32 = 2;
pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::core::ffi::c_long;
pub type uintmax_t = ::core::ffi::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_uuid {
    pub a: u32,
    pub b: u16,
    pub c: u16,
    pub d: [u8; 8usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_file {
    pub revision: u64,
    pub address: *mut ::core::ffi::c_void,
    pub size: u64,
    pub path: *mut ::core::ffi::c_char,
    pub string: *mut ::core::ffi::c_char,
    pub media_type: u32,
    pub unused: u32,
    pub tftp_ip: u32,
    pub tftp_port: u32,
    pub partition_index: u32,
    pub mbr_disk_id: u32,
    pub gpt_disk_uuid: limine_uuid,
    pub gpt_part_uuid: limine_uuid,
    pub part_uuid: limine_uuid,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_info_response {
    pub revision: u64,
    pub name: *mut ::core::ffi::c_char,
    pub version: *mut ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_info_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_bootloader_info_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_cmdline_response {
    pub revision: u64,
    pub cmdline: *mut ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_cmdline_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_executable_cmdline_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_firmware_type_response {
    pub revision: u64,
    pub firmware_type: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_firmware_type_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_firmware_type_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_stack_size_response {
    pub revision: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_stack_size_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_stack_size_response,
    pub stack_size: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_hhdm_response {
    pub revision: u64,
    pub offset: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_hhdm_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_hhdm_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_video_mode {
    pub pitch: u64,
    pub width: u64,
    pub height: u64,
    pub bpp: u16,
    pub memory_model: u8,
    pub red_mask_size: u8,
    pub red_mask_shift: u8,
    pub green_mask_size: u8,
    pub green_mask_shift: u8,
    pub blue_mask_size: u8,
    pub blue_mask_shift: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_framebuffer {
    pub address: *mut ::core::ffi::c_void,
    pub width: u64,
    pub height: u64,
    pub pitch: u64,
    pub bpp: u16,
    pub memory_model: u8,
    pub red_mask_size: u8,
    pub red_mask_shift: u8,
    pub green_mask_size: u8,
    pub green_mask_shift: u8,
    pub blue_mask_size: u8,
    pub blue_mask_shift: u8,
    pub unused: [u8; 7usize],
    pub edid_size: u64,
    pub edid: *mut ::core::ffi::c_void,
    pub mode_count: u64,
    pub modes: *mut *mut limine_video_mode,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_framebuffer_response {
    pub revision: u64,
    pub framebuffer_count: u64,
    pub framebuffers: *mut *mut limine_framebuffer,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_framebuffer_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_framebuffer_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_paging_mode_response {
    pub revision: u64,
    pub mode: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_paging_mode_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_paging_mode_response,
    pub mode: u64,
    pub max_mode: u64,
    pub min_mode: u64,
}
pub type limine_goto_address =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut limine_mp_info)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_mp_info {
    pub processor_id: u32,
    pub lapic_id: u32,
    pub reserved: u64,
    pub goto_address: limine_goto_address,
    pub extra_argument: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_mp_response {
    pub revision: u64,
    pub flags: u32,
    pub bsp_lapic_id: u32,
    pub cpu_count: u64,
    pub cpus: *mut *mut limine_mp_info,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_mp_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_mp_response,
    pub flags: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_memmap_entry {
    pub base: u64,
    pub length: u64,
    pub type_: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_memmap_response {
    pub revision: u64,
    pub entry_count: u64,
    pub entries: *mut *mut limine_memmap_entry,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_memmap_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_memmap_response,
}
pub type limine_entry_point = ::core::option::Option<unsafe extern "C" fn()>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_entry_point_response {
    pub revision: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_entry_point_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_entry_point_response,
    pub entry: limine_entry_point,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_file_response {
    pub revision: u64,
    pub executable_file: *mut limine_file,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_file_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_executable_file_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_internal_module {
    pub path: *const ::core::ffi::c_char,
    pub string: *const ::core::ffi::c_char,
    pub flags: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_module_response {
    pub revision: u64,
    pub module_count: u64,
    pub modules: *mut *mut limine_file,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_module_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_module_response,
    pub internal_module_count: u64,
    pub internal_modules: *mut *mut limine_internal_module,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_rsdp_response {
    pub revision: u64,
    pub address: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_rsdp_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_rsdp_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_smbios_response {
    pub revision: u64,
    pub entry_32: u64,
    pub entry_64: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_smbios_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_smbios_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_system_table_response {
    pub revision: u64,
    pub address: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_system_table_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_efi_system_table_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_memmap_response {
    pub revision: u64,
    pub memmap: *mut ::core::ffi::c_void,
    pub memmap_size: u64,
    pub desc_size: u64,
    pub desc_version: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_efi_memmap_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_efi_memmap_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_date_at_boot_response {
    pub revision: u64,
    pub timestamp: i64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_date_at_boot_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_date_at_boot_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_address_response {
    pub revision: u64,
    pub physical_base: u64,
    pub virtual_base: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_executable_address_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_executable_address_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_dtb_response {
    pub revision: u64,
    pub dtb_ptr: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_dtb_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_dtb_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_riscv_bsp_hartid_response {
    pub revision: u64,
    pub bsp_hartid: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_riscv_bsp_hartid_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_riscv_bsp_hartid_response,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_performance_response {
    pub revision: u64,
    pub reset_usec: u64,
    pub init_usec: u64,
    pub exec_usec: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct limine_bootloader_performance_request {
    pub id: [u64; 4usize],
    pub revision: u64,
    pub response: *mut limine_bootloader_performance_response,
}

// implementing the missing macros
pub const static LIMINE_REQUESTS_START_MARKER: [u64;4] = [
    0xf6b8f4b39de7d1ae, 0xfab91a6940fcb9cf,
    0x785c6ed015d3e316, 0x181e920a7852b9d9
];

pub const static LIMINE_REQUESTS_END_MARKER: [u64;2] = [
    0xadc0e0531bb10d03, 0x9572709f31764c62
];


pub const fn LIMINE_BASE_REVISION(N: u64) -> [u64;3] {
    [0xf9562b2d5c95a6c8, 0x6a7b384944536bdc, N];
}

pub const fn LIMINE_BASE_REVISION_SUPPORTED(VAR: [u64; 3]) -> bool {
    return VAR[2] == 0
}

pub const fn LIMINE_LOADED_BASE_REVISION_VALID(VAR: [u64; 3]) -> bool {
    return VAR[1] != 0x6a7b384944536bdc
}
pub const fn LIMINE_LOADED_BASE_REVISION(VAR: [u64; 3]) -> u64 {
    return VAR[1] == 0
}

pub const static LIMINE_COMMON_MAGIC: [u64;2] = [0xc7b1dd30df4c8b88, 0x0a82e883a194f07b];

pub const static LIMINE_BOOTLOADER_INFO_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0xf55038d8e2a1202f, 
    0x279426fcf5f59740
];


pub const static LIMINE_EXECUTABLE_CMDLINE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x4b161536e598651e, 
    0xb390ad4a2f1f303a
];


pub const static LIMINE_FIRMWARE_TYPE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x8c2f75d90bef28a8, 
    0x7045a4688eac00c3
];

pub const static LIMINE_STACK_SIZE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x224ef0460a8e8926, 
    0xe1cb0fc25f46ea3d
];

pub const static LIMINE_HHDM_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x48dcf1cb8ad2b852, 
    0x63984e959a98244b
];

pub const static LIMINE_FRAMEBUFFER_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x9d5827dcd881dd75, 
    0xa3148604f6fab11b
];

pub const static LIMINE_PAGING_MODE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x95c1a0edab0944cb, 
    0xa4e5cb3842f7488a
];

pub const static LIMINE_MP_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x95a67b819a1b857e, 
    0xa0b61b723b6a73e0
];

pub const static LIMINE_MEMMAP_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x67cf3d9d378a806f, 
    0xe304acdfc50c3c62
];

pub const static LIMINE_ENTRY_POINT_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x13d86c035a1cd3e1, 
    0x2b0caa89d8f3026a
];

pub const static LIMINE_EXECUTABLE_FILE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0xad97e90e83f1ed67, 
    0x31eb5d1c5ff23b69
];

pub const static LIMINE_MODULE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x3e7e279702be32af, 
    0xca1c4f3bd1280cee
];

pub const static LIMINE_RSDP_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0xc5e77b6b397e7b43, 
    0x27637845accdcf3c
];

pub const static LIMINE_SMBIOS_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x9e9046f11e095391, 
    0xaa4a520fefbde5ee
];

pub const static LIMINE_EFI_SYSTEM_TABLE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x5ceba5163eaaf6d6, 
    0x0a6981610cf65fcc
];

pub const static LIMINE_EFI_MEMMAP_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x7df62a431d6872d5, 
    0xa4fcdfb3e57306c8
];

pub const static LIMINE_DATE_AT_BOOT_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x502746e184c088aa, 
    0xfbc5ec83e6327893
];

pub const static LIMINE_EXECUTABLE_ADDRESS_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x71ba76863cc55f63, 
    0xb2644a48c516a487
];

pub const static LIMINE_DTB_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0xb40ddb48fb54bac7, 
    0x545081493f81ffb7
];

pub const static LIMINE_RISCV_BSP_HARTID_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x1369359f025525f9, 
    0x2ff2a56178391bb6
];

pub const static LIMINE_BOOTLOADER_PERFORMANCE_REQUEST_ID: [u64;4] = [
    LIMINE_COMMON_MAGIC[0],
    LIMINE_COMMON_MAGIC[1],
    0x6b50ad9bf36d13ad, 
    0xdc4c7e88fc759e17
];